---
title:  "Bakeman Foods"
author: "Tarun Shrivas"
date:   "November 26, 2017"
output: html_document
---

```{r echo = FALSE, message = FALSE, warning = FALSE, results = "hide"}

## Course:   ECON 5100: Statistical Applications and Quantitative Methods 
## Term:     Fall 2017 Quarter (17FQ)
## Title:    Bakeman Foods (modified HBR Case):     
## Purpose:  Individual Project: Application of forecasting models concepts  trend, seasonality, cyclicity                  
## Author:   Tarun Shrivas
## Clear the environmnet  
rm(list=ls(all=TRUE))
## Load the libraries   
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(forecast)
library(lmtest)
library(MLmetrics)
```

#### Data pre-processing:  

```{r,message = FALSE, warning = FALSE}
## Import Data
feast <- read.csv("Bakeman.csv", header=TRUE)
## Data structure
glimpse(feast)
## Rename column names
colnames(feast) <- c("mo", "cs","cp", "cp.1", "cp.2", "da", "da.1", "da.2", "si")
```

#### Time-series plot:  

```{r,message = FALSE, warning = FALSE}

## Time-Series plot 
p <- ggplot(data = feast, aes(x = mo, y = cs/1000)) 
plot1 <-  p + geom_line() + 
          geom_smooth(method = 'lm', se = FALSE)+ 
          geom_vline(xintercept = 12, linetype = "dashed", colour = "steelblue")+
          geom_vline(xintercept = 24, linetype = "dashed", colour = "steelblue")+
          geom_vline(xintercept = 36, linetype = "dashed", colour = "steelblue")+
          geom_vline(xintercept = 48, linetype = "dashed", colour = "steelblue")+
          geom_vline(xintercept = 60, linetype = "dashed", colour = "steelblue")+
          labs(x = "months \n(1: Jan'83, 60: Dec'87)", y = "(Case Shipments)months (in '000s)")+  
          ggtitle("Case Shipments Time Series Plot") + 
          scale_x_discrete(limits = c(1:60)) +  
          theme_minimal() +
          theme(plot.title = element_text(hjust = 0.5)) 

## Plot 
plot1
## Copy the plot to a PNG file "Case Shipments.png"  
dev.copy(png, file = "Plot1_Case_Shipments.png", height= 300, width = 1024)
## Close the PNG device
dev.off()

```


#### Regression Model: 

```{r,message = FALSE, warning = FALSE}

## Monthly Sales (i.e. "Case Shimpents") are influenced by:  
## Time (Month) 
## Consumer Promotions (cp) and Dealer Allowances (da) during the given month
## Consumer Promotions and Dealer Allowances during the previous months (cp.1, cp.2, da.1 and da.2)
## Seasonality (si)

## Using step-wise regression model 
model1 <- step(lm(cs ~ mo + cp + cp.1 + cp.2 + da + da.1 + da.2 + si, data = feast, na.action = na.exclude))
## Present Parameter Estimates, Coefficient of Determination, etc.
summary(model1)

```


#### Conduct Durbin - Watson Test:

```{r,message = FALSE, warning = FALSE}

## Conduct Durbin Watson Test
dwtest(model1, order.by = NULL, alternative = c("two.sided"))

```


#### Residuals' Plots:

```{r,message = FALSE, warning = FALSE}

standardized.residual <- rstandard(model1)
predicted <- predict(model1)/1000
mo <- feast$mo 
predicts <- as.data.frame(cbind(mo, predicted, standardized.residual))
#par(mfrow = c(1,2), mar = c(4,4,2,1), oma = c(0,0,2,0))

p_left <- ggplot(predicts, aes(predicted, standardized.residual)) + 
          geom_point(colour = "steelblue") + 
          geom_hline(yintercept = 2, linetype = "dashed", colour = "red")+
          geom_hline(yintercept = -2, linetype = "dashed", colour = "red")+
          labs(x = "Predicted Case Shipments (in '000s)", y = "Standardized Residuals")+ 
          scale_x_continuous(limits = c(0,800))+
          theme_bw() +       
          theme(legend.position="none") 


p_right <-  ggplot(predicts, aes(mo, standardized.residual)) + 
            geom_point(colour = "steelblue") + 
            geom_hline(yintercept = 2, linetype = "dashed", colour = "red")+
            geom_hline(yintercept = -2, linetype = "dashed", colour = "red")+
            geom_vline(xintercept = 17, linetype = "dashed", colour = "steelblue")+
            geom_text(x = 19, y = 1.0, label = "month = 17", color = "darkgoldenrod4", angle = 90) +             
            geom_vline(xintercept = 41, linetype = "dashed", colour = "steelblue")+
            geom_text(x = 43, y = 0, label = "month = 41", color = "darkgoldenrod4", angle = 90) +  
            labs(x = "months", y = "Standardized Residuals")+ 
            scale_x_continuous(limits = c(0,62))+
            theme_bw() +
            theme(legend.position="none")

grid.arrange(p_left, p_right, top = "Standardized Residulas vs. Predicted Values",
            layout_matrix = matrix(c(1,2), ncol=2, byrow=TRUE))
 
png("Plot2_Standardized_Residulas_vs._Predicted_Values.png", height= 300, width = 1024) 
grid.arrange(p_left, p_right, top = "Standardized Residulas vs. Predicted Values",
            layout_matrix = matrix(c(1,2), ncol=2, byrow=TRUE))
dev.off()

```


#### Time-Series plot: Predicted vs. Actual   

```{r,message = FALSE, warning = FALSE}

plot3 <- ggplot(feast, aes(mo)) + 
         geom_line(aes(y = cs/1000, colour = "Actual"), size = 1.0) + 
         geom_line(aes(y = fitted(model1)/1000, colour = "Predicted"), size = 1.0)+
         labs(x = "months \n(1: Jan'83, 60: Dec'87)", y = "(Case Shipments)months (in '000s)")+  
         ggtitle("Case Shipments : Predicted vs. Actual") + 
         scale_x_discrete(limits = c(1:60)) +  
         theme_minimal() +
         theme(plot.title = element_text(hjust = 0.5))+
         theme(legend.position="top") + theme(legend.title=element_blank())

## Plot 
plot3
## Copy the plot to a PNG file "Case Shipments.png"  
dev.copy(png, file = "Plot3_Predicted_vs_Actual.png", height= 300, width = 1024)
## Close the PNG device
dev.off()

```


#### Mean Absolute Percentage Error: MAPE

```{r,message = FALSE, warning = FALSE}
# MAPE of forecast 
actual <- feast$cs
predicted <- fitted(model1)
MAPE(predicted[13:60], actual[13:60])

```



#### Predictions: 

```{r,message = FALSE, warning = FALSE}
## Make prediction and compute confidence interval
n <- nrow(feast)    # number of observatons 
forecast(model1, newdata = feast[n, ])

```


*Point Forecast* | *Lo 80*   |   *Hi 80*   |  *Lo 95*  |  *Hi 95*    
 ---------------- |  -------  |  --------   |  -------  | ---------
     501189.2     | 452432.5  |  549945.9   |  425593.9 | 576784.5




#### Customized Plot To be Used AS Header  

```{r, message=FALSE, warning=FALSE}
library(ggthemes)

plot4 <- ggplot(feast, aes(x = mo)) + 
         geom_point(aes(y = cs/1000, colour = "Actual Sales"), size = 5, alpha = 1/3) + 
         geom_point(aes(y = fitted(model1)/1000, colour = "Sales Forecast"), size = 5, alpha = 1/3)+
         labs(x = "Months ( 1:Jan'83 -to- 60:Dec'87)", y = "Sales  (volume)")+  
         theme_stata()+
         theme(legend.position=c(0.10,0.90)) + theme(legend.title=element_blank())
         



## Plot 
plot4
## Copy the plot to a PNG file "Case Shipments.png"  
dev.copy(png, file = "Header.png", height= 300, width = 1024)
## Close the PNG device
dev.off()

```




